# Generated by Django 4.1.5 on 2023-01-24 11:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shoppinglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='additional_users',
            field=models.ManyToManyField(related_name='additional_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
