# Generated by Django 4.1.5 on 2023-01-25 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_shoppinglist_additional_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglist',
            name='additional_users',
            field=models.ManyToManyField(blank=True, related_name='additional_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_time_used', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='items',
            field=models.ManyToManyField(to='core.item'),
        ),
    ]
