# Generated by Django 4.1.5 on 2023-01-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_shoppinglist_additional_users_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='last_time_used',
            field=models.DateTimeField(blank=True),
        ),
    ]
