# Generated by Django 4.1.5 on 2023-01-25 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_item_last_time_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='food_type',
            field=models.CharField(blank=True, choices=[('vegetables', 'vegetables'), ('fruits', 'fruits'), ('grains, beans and nuts', 'grains, beans and nuts'), ('meat and poultry', 'meat and poultry'), ('fish and seafood', 'fish and seafood'), ('dairy foods', 'dairy foods'), ('fat', 'fat'), ('sweets', 'sweets')], max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_time_used',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 25, 9, 43, 58, 300240, tzinfo=datetime.timezone.utc)),
        ),
    ]
